Repository AY2425S1-CS2113-T10-2/tp, pull requests merged in 2024-11, with the labels that each got.

#357 Add formatting for phone number
  src/main/java/bookbob/functions/CommandHandler.java
Labels: type.Bug, severity.Low

#369 guard against duplicate visits for "addVisit" command
  src/main/java/bookbob/Main.java
  src/main/java/bookbob/functions/CommandHandler.java
  src/main/java/bookbob/parser/Parser.java
Labels: type.Task, priority.Medium

#376 "addVisit" command prevents addition of future dates.
  docs/UserGuide.md
  src/main/java/bookbob/functions/CommandHandler.java
Labels: priority.Medium

#388 fix "find" finding DOB
  docs/UserGuide.md
  src/main/java/bookbob/functions/CommandHandler.java
  src/test/java/bookbob/functions/CommandHandlerTest.java
Labels: type.Bug, priority.High
